export const en = {
  shopTagline: "Fresh beverages, delivered to your door", admin: "Admin", catAll: "All",
  catEspresso: "Coffee", catCold: "Non-Coffee",
  beanHouse: "House Blend", beanLight: "Light Roast (+฿10)", milkFresh: "Fresh Milk", milkOat: "Oat Milk (+฿10)",
  optHot: "Hot", optIced: "Iced",
  standard: "Standard", cart: "Your Cart", emptyCart: "Cart is empty.", total: "Total", proceedCheckout: "Proceed to Checkout →", yourDetails: "Your Details", namePH: "Your name *", unitLabel: "Delivery Unit *", notePH: "Special instructions (optional)", proceedPayment: "Proceed to Payment →", scanToPay: "📱 Scan QR to Pay", totalAmt: "Total Amount", attachSlip: "📎 Attach slip screenshot (required):", tapUpload: "📷 Tap to upload screenshot", maxSize: "(max 10MB)", removeSlip: "✕ Remove", confirmPayment: "✅ Confirm Payment & Place Order", backCart: "← Back to Cart", back: "← Back", viewCart: "View Cart →", items: "items", orderLabel: "Order", hide: "▲ Hide", showDetails: "▼ Details", orderedItems: "Items ordered:", slipRejectedMsg: "⚠️ Payment could not be verified. Please upload a clear screenshot.", uploadNewSlip: "📷 Upload new slip", submitNewSlip: "📤 Submit New Slip", slipSubmittedOk: "✅ New slip submitted! Please wait for verification.", statusPending: "Verifying payment slip 🔍", statusPreparing: "Brewing your order ☕", statusDelivering: "On the way to your unit! 🚶", statusCompleted: "Delivered — enjoy! 🎉", statusRejected: "Slip rejected — re-upload ⚠️", staffLogin: "Staff Login", pwPH: "Password", loginBtn: "Login", backToMenu: "← Back to Menu", wrongPw: "Wrong password!", dashboard: "👨‍🍳 Order Dashboard", showCompleted: "Show completed", refresh: "🔄 Refresh", exit: "← Exit", statTotal: "Total", statPending: "Pending", statBrewing: "Preparing", statDone: "Done", noCompleted: "No completed orders yet.", noActive: "No active orders.", verifyBrew: "✅ Verify Slip & Prepare", rejectSlip: "❌ Reject Slip", markDelivering: "🚶 Mark Delivering", markDelivered: "✅ Mark Delivered", awaitSlip: "Awaiting new slip from customer...", delConfirm: "Permanently delete this order?", slipLabel: "💳 Payment Slip:", clickEnlarge: "Click to enlarge", unitPrefix: "Unit:",
  menuNames: { 1: "Classic Espresso", 2: "Creamy Latte", 3: "Cappuccino", 4: "Americano", 5: "Flat White", 6: "Caramel Macchiato", 7: "Premium Cocoa", 8: "Matcha Latte", 9: "Strawberry Soda", 10: "Peach Soda", 11: "Blue Hawaii", 12: "Lemon Tea" },
  menuDescs: { 1: "Rich & bold single shot", 2: "Espresso with silky steamed milk", 3: "Espresso, steamed milk & foam", 4: "Espresso with hot water — no milk", 5: "Double ristretto & velvety milk", 6: "Vanilla, milk, espresso & caramel", 7: "Rich and smooth chocolate", 8: "Authentic Japanese green tea", 9: "Fizzy and refreshing strawberry", 10: "Sweet and sparkling peach", 11: "Tropical blue citrus soda", 12: "Refreshing iced lemon tea" },
  submitting: "Processing..."
};
